services:
  - type: web
    runtime: node
    name: eluminatium
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APPS_DIR
        value: ./apps
      - key: UI_DIR
        value: ./apps/eluminatium-ui
      - key: CORS_ORIGIN
        generateValue: true
